name: tests
on:
  push:
    branches:
      - main
      - test-me-*
  pull_request:
  schedule:
    - cron: "0 8 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: true
      matrix:
        os: ['Ubuntu', 'MacOs', 'Windows']
    uses: asottile/workflows/.github/workflows/tox.yml@v1.2.0
    with:
      env: '["py37", "py38", "py39", "py310", "py311"]'
      os: ${{ matrix.os }}-latest
