name: tests
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          - MacOs
          - Windows
        py:
          - "3.10"
          - "3.9"
          - "3.8"
          - "3.7"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v3
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox -vv --notest
      - name: Run test suite
        run: tox r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
